-- Portfolio Tracker database schema
-- Target database: SQL Server
--
-- Create a database first, for example:
-- CREATE DATABASE PortfolioTracker;
-- GO
-- USE PortfolioTracker;
-- GO

CREATE TABLE USUARIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EMAIL NVARCHAR(255) UNIQUE NOT NULL,
    USERNAME NVARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    IS_ACTIVE BIT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_AT DATETIME2 NOT NULL DEFAULT GETDATE()
);

CREATE TABLE ACTIVOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_ACTIVO NVARCHAR(20) NOT NULL,
    SIMBOLO NVARCHAR(30) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    API_ID NVARCHAR(100) NULL,
    FUENTE NVARCHAR(50) NULL,
    IS_ACTIVE BIT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),

    CONSTRAINT CHK_ACTIVOS_TIPO
        CHECK (TIPO_ACTIVO IN ('CRYPTO', 'STOCK')),

    CONSTRAINT UQ_ACTIVOS_TIPO_SIMBOLO
        UNIQUE (TIPO_ACTIVO, SIMBOLO)
);

CREATE TABLE FAVORITOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    ACTIVO_ID INT NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_FAVORITOS_USUARIOS
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),

    CONSTRAINT FK_FAVORITOS_ACTIVOS
        FOREIGN KEY (ACTIVO_ID) REFERENCES ACTIVOS(ID),

    CONSTRAINT UQ_FAVORITOS_USUARIO_ACTIVO
        UNIQUE (USUARIO_ID, ACTIVO_ID)
);

CREATE TABLE PORTFOLIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    ICONO NVARCHAR(10) NULL,
    DESCRIPCION NVARCHAR(255) NULL,
    ES_DEFAULT BIT NOT NULL DEFAULT 0,
    IS_ACTIVE BIT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_PORTFOLIOS_USUARIOS
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),

    CONSTRAINT UQ_PORTFOLIOS_USUARIO_NOMBRE
        UNIQUE (USUARIO_ID, NOMBRE),

    CONSTRAINT CHK_PORTFOLIOS_NOMBRE_NO_VACIO
        CHECK (LEN(LTRIM(RTRIM(NOMBRE))) > 0)
);

CREATE TABLE TRANSACCIONES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    PORTFOLIO_ID INT NOT NULL,
    ACTIVO_ID INT NOT NULL,
    TIPO_TRANSACCION NVARCHAR(20) NOT NULL,
    TIPO_TRANSFERENCIA NVARCHAR(20) NULL,
    CANTIDAD DECIMAL(28,10) NOT NULL,
    PRECIO_UNITARIO DECIMAL(28,10) NOT NULL DEFAULT 0,
    IMPORTE_TOTAL DECIMAL(28,10) NOT NULL DEFAULT 0,
    MONEDA_FIAT NVARCHAR(10) NOT NULL DEFAULT 'USD',
    FECHA_TRANSACCION DATETIME2 NOT NULL,
    NOTAS NVARCHAR(255) NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_TRANSACCIONES_PORTFOLIOS
        FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIOS(ID),

    CONSTRAINT FK_TRANSACCIONES_ACTIVOS
        FOREIGN KEY (ACTIVO_ID) REFERENCES ACTIVOS(ID),

    CONSTRAINT CHK_TRANSACCIONES_TIPO
        CHECK (TIPO_TRANSACCION IN ('BUY', 'SELL', 'TRANSFER')),

    CONSTRAINT CHK_TRANSACCIONES_TRANSFERENCIA
        CHECK (
            TIPO_TRANSFERENCIA IS NULL
            OR TIPO_TRANSFERENCIA IN ('IN', 'OUT')
        ),

    CONSTRAINT CHK_TRANSACCIONES_COHERENCIA
        CHECK (
            (TIPO_TRANSACCION IN ('BUY', 'SELL') AND TIPO_TRANSFERENCIA IS NULL)
            OR
            (TIPO_TRANSACCION = 'TRANSFER' AND TIPO_TRANSFERENCIA IN ('IN', 'OUT'))
        ),

    CONSTRAINT CHK_TRANSACCIONES_CANTIDAD
        CHECK (CANTIDAD > 0),

    CONSTRAINT CHK_TRANSACCIONES_PRECIO
        CHECK (PRECIO_UNITARIO >= 0),

    CONSTRAINT CHK_TRANSACCIONES_IMPORTE
        CHECK (IMPORTE_TOTAL >= 0)
);
